/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-09-07 19:29:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registrCl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!Doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<link rel=\"icon\" href=\"images/pen.ico\" type=\"image/x-icon\">\r\n");
      out.write("\t\t<title>Kugo</title>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<!-- Latest compiled and minified CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"css.css\">\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"jquery-1.11.1.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"toTranslate.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<ul id=\"topmenu\">\r\n");
      out.write("\t\t\t\t<li class=\"logo\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/logo_264x7.png\" onclick='window.location=\"index.jsp\"'>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div id=\"enject\" >\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/enject_small.png\" >\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class='sign-in'>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default navbar-btn\">Sign in</button>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"top_filler\"></div>\r\n");
      out.write("\t\t<div class=\"registr-nav\">\r\n");
      out.write("\t\t\t<div><b>Three steps to do a translation</b></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"iconItem\">\r\n");
      out.write("\t\t\t\t<img class=\"r-icon sel\" src=\"images/1-to-translate.png\" onclick='window.location = \"registrCl.jsp\"'>\r\n");
      out.write("\t\t\t\t<div>Chose<br>language and<br>type of translation</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<img class=\"r-span\" src=\"images/arrow-icon.png\">\r\n");
      out.write("\t\t\t<div class=\"iconItem\">\r\n");
      out.write("\t\t\t\t<img class=\"r-icon\" src=\"images/2-to-translate.png\" onclick='window.location = \"secondStep.jsp\"'>\r\n");
      out.write("\t\t\t\t<div>Upload<br>file or type<br>your text</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<img class=\"r-span\" src=\"images/arrow-icon.png\">\r\n");
      out.write("\t\t\t<div class=\"iconItem\">\r\n");
      out.write("\t\t\t\t<img class=\"r-icon\" src=\"images/3-to-translate.png\" onclick='window.location = \"thirdStep.jsp\"'>\r\n");
      out.write("\t\t\t\t<div>Pay<br>and take your<br>delivery</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"choose-container\">\r\n");
      out.write("\t\t\t<form class=\"lang-form\">\r\n");
      out.write("\t\t\t<label style=\"text-align:center\">Chose language</label><br>\r\n");
      out.write("\t\t\t\t<div class=\"source-container\">\r\n");
      out.write("\t\t\t\t\t<label>Source:</label>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"lan-src\" id=\"ukr\" value=\"Ukrainian\" />\r\n");
      out.write("\t\t\t\t\t\t<label for=\"ukr\">Ukrainian</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"lan-src\" id=\"rus\"  value=\"Russian\"/>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"ukr\">Russian</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"lan-src\" id=\"eng\" value=\"English\"/>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"ukr\">English</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"source-container\">\r\n");
      out.write("\t\t\t\t\t<label>Target:</label>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox\" id=\"ukr\"  value=\"Ukrainian\"/>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"ukr\">Ukrainian</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox\" id=\"rus\"  value=\"Russian\"/>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"ukr\">Russian</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox\" id=\"eng\" value=\"English\"/>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"ukr\">English</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button class=\"save-lang\" onclick=\"return false;\">Move on!</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<div class=\"choose-container\" style=\"margin-top: 40px\">\r\n");
      out.write("\t\t\t<form class=\"lang-form\">\r\n");
      out.write("\t\t\t<label>Chose a type of translation</label><br>\r\n");
      out.write("\t\t\t\t<div class=\"source-container\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox\" id=\"ukr\" value=\"General\" />\r\n");
      out.write("\t\t\t\t\t\t<label for=\"ukr\">General</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"source-container\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox\" id=\"ukr\"  value=\"Specific\"/>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"ukr\">Specific</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox\" id=\"rus\"  value=\"Technology\"/>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"ukr\">Technology</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox\" id=\"eng\" value=\"Medicine\"/>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"ukr\">Medicine</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox\" id=\"eng\" value=\"Literature\"/>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"ukr\">Literature</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox\" id=\"eng\" value=\"Law\"/>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"ukr\">Law</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox\" id=\"eng\" value=\"Economix/Finance\"/>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"ukr\">Economix/Finance</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox\" id=\"eng\" value=\"IT\"/>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"ukr\">IT</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button class=\"save-type\" onclick=\"return false;\">Move on!</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"choose_container\">\t\r\n");
      out.write("\t    <div class=\"quality_level\">\r\n");
      out.write("\t       <b>Standart</b>\r\n");
      out.write("\t       <br>\r\n");
      out.write("\t       Recommended for\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\teveryday context\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t50hm/1 translation page\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div style=\"display:inline-block\">\r\n");
      out.write("\t\t\t\t<input style=\"text-align:center\" type=\"radio\" id=\"str\" name=\"quality\" value=\"Standart\" />\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("   \r\n");
      out.write("\t\t\t <div class=\"quality_level\">\r\n");
      out.write("\t       <b>Business</b>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\tRecommended for\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\tbusiness context\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t75hm/1 translation page\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div style=\"display:inline-block\">\r\n");
      out.write("\t\t\t\t<input style=\"text-align:center\" type=\"radio\" id=\"buss\" name=\"quality\" value=\"Business\" />\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t    <div class=\"quality_level\">\r\n");
      out.write("\t       <b>Extra</b>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\tRecommended for\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\tscientific materials\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t150hm/1 translation page\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div style=\"display:inline-block\">\r\n");
      out.write("\t\t\t\t<input style=\"text-align:center\" type=\"radio\" id=\"extr\" name=\"quality\" value=\"Extra\" />\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t   </div>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button class=\"\" onclick=\"return false;\">Send Data</button>\r\n");
      out.write("\t</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
