--<ScriptOptions statementTerminator=";"/>

CREATE TABLE PUBLIC.QUALITY (
		ID INTEGER NOT NULL,
		QUALITY VARCHAR(45) NOT NULL
	);

CREATE TABLE PUBLIC.ORDERS (
		ID INTEGER NOT NULL,
		USER VARCHAR(45) NOT NULL,
		SOURCE INTEGER NOT NULL,
		TYPE INTEGER,
		QUALITY INTEGER,
		FILE BLOB(2147483647),
		ADD BLOB(2147483647),
		SYMBOLS INTEGER,
		FORMED_DATE TIMESTAMP,
		FINISH_DATE TIMESTAMP
	);

CREATE TABLE PUBLIC.LOGINS (
		EMAIL VARCHAR(45) NOT NULL,
		PASS VARCHAR(45) NOT NULL
	);

CREATE TABLE PUBLIC.TARGET (
		ORDER_ID INTEGER NOT NULL,
		TARGET INTEGER NOT NULL
	);

CREATE TABLE PUBLIC.TYPE (
		ID INTEGER NOT NULL,
		TYPE VARCHAR(45) NOT NULL
	);

CREATE TABLE PUBLIC.LANG (
		ID INTEGER NOT NULL,
		LANG VARCHAR(45) NOT NULL
	);

CREATE UNIQUE INDEX PUBLIC.PRIMARY_KEY_8B ON PUBLIC.ORDERS (ID ASC);

CREATE UNIQUE INDEX PUBLIC.CONSTRAINT_INDEX_51 ON PUBLIC.QUALITY (QUALITY ASC);

CREATE UNIQUE INDEX PUBLIC.CONSTRAINT_INDEX_5 ON PUBLIC.QUALITY (ID ASC);

CREATE UNIQUE INDEX PUBLIC.CONSTRAINT_INDEX_9 ON PUBLIC.TARGET (ORDER_ID ASC);

CREATE UNIQUE INDEX PUBLIC.CONSTRAINT_INDEX_2 ON PUBLIC.LANG (ID ASC);

CREATE UNIQUE INDEX PUBLIC.CONSTRAINT_INDEX_23 ON PUBLIC.LANG (LANG ASC);

CREATE UNIQUE INDEX PUBLIC.CONSTRAINT_INDEX_8 ON PUBLIC.LOGINS (EMAIL ASC);

CREATE UNIQUE INDEX PUBLIC.PRIMARY_KEY_2 ON PUBLIC.LANG (ID ASC);

CREATE UNIQUE INDEX PUBLIC.CONSTRAINT_INDEX_93 ON PUBLIC.TARGET (TARGET ASC);

CREATE UNIQUE INDEX PUBLIC.PRIMARY_KEY_9 ON PUBLIC.TARGET (ORDER_ID ASC);

CREATE UNIQUE INDEX PUBLIC.CONSTRAINT_INDEX_27 ON PUBLIC.TYPE (ID ASC);

CREATE UNIQUE INDEX PUBLIC.PRIMARY_KEY_5 ON PUBLIC.QUALITY (ID ASC);

CREATE UNIQUE INDEX PUBLIC.CONSTRAINT_INDEX_8B7 ON PUBLIC.ORDERS (USER ASC);

CREATE UNIQUE INDEX PUBLIC.PRIMARY_KEY_8 ON PUBLIC.LOGINS (EMAIL ASC);

CREATE UNIQUE INDEX PUBLIC.CONSTRAINT_INDEX_8B ON PUBLIC.ORDERS (ID ASC);

CREATE UNIQUE INDEX PUBLIC.PRIMARY_KEY_27 ON PUBLIC.TYPE (ID ASC);

CREATE UNIQUE INDEX PUBLIC.CONSTRAINT_INDEX_278 ON PUBLIC.TYPE (TYPE ASC);

ALTER TABLE PUBLIC.LOGINS ADD CONSTRAINT CONSTRAINT_86 PRIMARY KEY (EMAIL);

ALTER TABLE PUBLIC.TYPE ADD CONSTRAINT CONSTRAINT_2787 PRIMARY KEY (ID);

ALTER TABLE PUBLIC.QUALITY ADD CONSTRAINT CONSTRAINT_519 PRIMARY KEY (ID);

ALTER TABLE PUBLIC.ORDERS ADD CONSTRAINT CONSTRAINT_8B72 PRIMARY KEY (ID);

ALTER TABLE PUBLIC.LANG ADD CONSTRAINT CONSTRAINT_238 PRIMARY KEY (ID);

ALTER TABLE PUBLIC.TARGET ADD CONSTRAINT CONSTRAINT_931 PRIMARY KEY (ORDER_ID);

